[package]
name = "whirm"
version = "0.1.0"
description = "A desktop app to manage your proxies, switch between them, and route your network traffic with ease."
authors = ["S0lide <olide754@gmail.com>"]
license = "MIT"
repository = "https://github.com/Sol1de/Whirm"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.6", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11", features = [] }
tauri-plugin-log = "2"
sysproxy = "0.3"
reqwest = { version = "0.13.3", features = ["rustls", "socks"] }
tokio = { version = "1.52.1", features = ["full"] }
urlencoding = "2"
